# User config for `sleepscore` call"""

# Path to Dataset
binPath: "/Users/tom/data/neuropixels/11-25-2019_g2/10-25-2019_g2_imec0/10-25-2019_g2_t0.imec0.lf.bin"
datatype: 'SGLX'

# Downsampling frequency
downSample: 100.0  # (Hz)

# Duration of the segment of data loaded
tStart: 0.0  # 0 (s)
tEnd: null  # (s) / end of recording if None

# Loaded channels
chanList: [0] # All channels if `None`
chanListType: 'indices'  # How are values in `chanList` interpreted? See doc
chanLabelsMap: null  # Map channel relabelling (keys are values in `chanList`)

# Unit of returned data
unit: 'uV'  # 'uV' or 'mV'

# Derived EMG
add_EMG: False  # Ignore all EMG-related stuff or not
save_EMG: True  # Save EMG if we (re)compute it
recompute_EMG: False  # Force recomputing of EMG
EMG_config:
  sf: null  # If null, we use the `downSample` parameter
  window_size: 25.0  # Window size in ms for xcorr computing
  bandpass: [300, 600]
  bandstop: [275, 625]
  LFP_downsample: null  # sf of LFP used when computing xcorr. 
  LFP_chanList: []  # eg: [0, -2] Which channels are used for EMG computing
  LFP_chanListType: 'indices'  # How are values in `chanList` interpreted?

# Arguments passed to the `Sleep` GUI
kwargs_sleep: {
  downsample: null,
}
