# User config for `sleepscore` call"""

# Path to Dataset
binPath: "/Users/tom/data/neuropixels/11-25-2019_g2/10-25-2019_g2_imec0/10-25-2019_g2_t0.imec0.lf.bin"
datatype: 'SGLX'

# Downsampling frequency
downSample: 100.0  # (Hz)

# Duration of the segment of data loaded
tStart: 0.0  # 0 (s)
tEnd: null  # (s) / end of recording if None

# Loaded channels
chanList: [] # All channels loaded if `None` or 'all'. eg: ["LF0;384", "LF1;385"] (If chanListType = 'labels'), or [0, 1, -1] (If chanListType = 'indices')
chanListType: 'labels'  # How are values in `chanList` interpreted? ('indices' or 'labels')
chanLabelsMap: null  # Mapping for  channel relabelling (keys are channel labels). eg: {"LF0;384": 'cortex'}

# Unit of returned data
unit: 'uV'  # 'uV' or 'mV'

# Derived EMG
add_EMG: False  # Ignore all EMG-related stuff or not
save_EMG: True  # Save EMG if we (re)compute it
recompute_EMG: False  # Force recomputing of EMG
EMG_config:
  sf: null  # If null, we use the `downSample` parameter
  window_size: 25.0  # Window size in ms for xcorr computing
  bandpass: [300, 600]
  bandstop: [275, 625]
  LFP_downsample: null  # sf of LFP used when computing xcorr. 
  LFP_chanList: []  # eg: [0, -2] Which channels are used for EMG computing
  LFP_chanListType: 'indices'  # How are values in `chanList` interpreted?

# Arguments passed to the `Sleep` GUI
kwargs_sleep: {
  downsample: null,  # Further downsample
  preload: False,  # Preload dataset in memory? Useful for large datasets ?
}
