# User config for `sleepscore` call"""

# Loaded data
datasets:
  -
    binPath: ''  # Path to bin ('SGLX') or block directory ('TDT'). Must be single-quoted.
    datatype: ''  # 'SGLX' or 'TDT'
    chanList: [] # List of labels of loaded channels. See doc. eg: ["LF0;384", "LF1;385"] (SGLX) or [LFPs-1, LFPs-2, EEGs-1, EMGs-1] (TDT)
    chanLabelsMap: null  # Mapping for  channel relabelling (keys are values in chanList). eg: {"LF0;384": 'cortex'}
    name: null  # Name of dataset. Prepended to channel labels (after relabelling) if specified and non-empty.

# Downsampling frequency
downSample: 100.0  # (Hz)
ds_method: 'interpolation'  # Passed to resample.signal_resample. 'poly' is more accurate but slow, 'interpolation' is fast

# Duration of the segment of data loaded
tStart: 0.0  # 0 (s)
tEnd: null  # (s) / end of recording if None

# Derived EMG added to the data. You must include the .npy extension when specifying the path.
EMGdatapath: null

# Arguments passed to the `Sleep` GUI
kwargs_sleep: {
  # downsample: null,  # Further downsample
  # annotations: 'path/to/myannotations.txt'
  # states_config_file: 'path/to/states_cfg.yml'  # Specify custom vigilance states here. Example : `https://github.com/TomBugnon/visbrain/blob/develop/examples/gui_sleep/example_states_cfg.yml`
  # video_file: 'path/to/video.avi'  # Sleep can display a video locked to the data.
  # video_offset: null,  #  Offset between start of video and start of data
}
